config/routes.rb
WSMA::Application.routes.draw do

  resources :houses
  resources :chores
  resources :shifts
  resources :assignments
  resources :fining_periods
  resources :fines
  resources :preferences
  resources :user_hour_requirements
  resources :house_hour_requirements
  resources :houses
  resources :users

  match "/login" => "users#login"
  match "/logout" => "users#logout"
  match "/forgot_password" => "users#forgot_password"
  match "/reset_password" => "users#reset_password"

  match "/admin" => "admin#index"
  match "/admin/set_admin_active_house" => "admin#set_admin_active_house"

  match "/user/managefines" => "users#manage"
  match "/user/profile" => "users#find_profile"
  match "/user/register" => "users#register"
  match "/user/managers" => "users#managers"
  match "/user/myshift" => "users#myshift"
  match "/users/:id/profile" => "users#profile"
  match "/users/:id/change_password/" => "users#change_password"

  match "/manageshifts" => "shifts#manageshifts"
  match "/createChore" => "chores#createChore"
  match "/quickassign" => "assignments#quickcreate"
  match "users/find_by_name/:name" => "users#find_by_name"
  match "assignments/find/:shift_id/:user_id" => "assignments#find"
  match "/setprefs" => "preferences#set_prefs"
  match "/createprefs" => "preferences#create_prefs"

  match "/demo/advance_time"
  match "/demo/mock_time"
  match "/demo/real_time"

  resources :demo
  match "/demo/chores" => "chores#new"
  match "/demo/myshift" => "users#myshift"

    root :to => 'demo#index'

end

app/models/fining_period.rb
class FiningPeriod < ActiveRecord::Base
  
  after_create :schedule_blow_off_job
  before_destroy :cancel_jobs
  
  belongs_to :house
  has_many :fines, :dependent => :destroy
  
  validates_presence_of :fining_week, :fine_for_hours_below, :fine_per_hour_below, :forgive_percentage_of_fined_hours
  
  validates_numericality_of :fining_week, :fine_per_hour_below, :greater_than_or_equal_to => 0
  
  validates_numericality_of :fine_for_hours_below, :less_than_or_equal_to => 0
  
  validates_numericality_of :forgive_percentage_of_fined_hours, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 1

  def schedule_blow_off_job
    tag = TimeProvider.generate_job_tag(self)
    TimeProvider.schedule_execute_at(calculate_fines_time, tag, self.class.to_s, self.id)
  end

  def execute_job
    calculate_fines
  end
  
  def calculate_fines_time
    return house.end_of_week(fining_week).advance(:hours => house.sign_off_by_hours_after.to_r)
  end
  
  def cancel_jobs
    tag = TimeProvider.generate_job_tag(self)
    TimeProvider.unschedule_task tag
  end
  
  def calculate_fines
    house.users.all.each do |u|
      if u.hour_balance < self.fine_for_hours_below
        f = Fine.create(:user => u, :amount => (fine_for_hours_below - u.hour_balance)*fine_per_hour_below, :paid => 0, :paid_date => nil, :hours_fined_for => (fine_for_hours_below - u.hour_balance))
      end
    end
  end

end

app/controllers/fining_periods_controller.rb
class FiningPeriodsController < ApplicationController

  # GET /fining_periods
  # GET /fining_periods.json
  def index
    @fining_periods = FiningPeriod.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @fining_periods }
    end
  end

  # GET /fining_periods/1
  # GET /fining_periods/1.json
  def show
    @fining_period = FiningPeriod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @fining_period }
    end
  end

  # GET /fining_periods/new
  # GET /fining_periods/new.json
  def new
    @fining_period = FiningPeriod.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @fining_period }
    end
  end

  # GET /fining_periods/1/edit
  def edit
    @fining_period = FiningPeriod.find(params[:id])
  end

  # POST /fining_periods
  # POST /fining_periods.json
  def create
    @fining_period = FiningPeriod.new(params[:fining_period])

    respond_to do |format|
      if @fining_period.save
        format.html { redirect_to @fining_period, :notice => 'Fining period was successfully created.' }
        format.json { render :json => @fining_period, :status => :created, :location => @fining_period }
      else
        format.html { render :action => "new" }
        format.json { render :json => @fining_period.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fining_periods/1
  # PUT /fining_periods/1.json
  def update
    @fining_period = FiningPeriod.find(params[:id])

    respond_to do |format|
      if @fining_period.update_attributes(params[:fining_period])
        format.html { redirect_to @fining_period, :notice => 'Fining period was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @fining_period.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fining_periods/1
  # DELETE /fining_periods/1.json
  def destroy
    @fining_period = FiningPeriod.find(params[:id])
    @fining_period.destroy

    respond_to do |format|
      format.html { redirect_to fining_periods_url }
      format.json { head :ok }
    end
  end
end

app/helpers/fining_periods_helper.rb
module FiningPeriodsHelper
end

app/views/fining_periods/_form.html.erb
<%= form_for(@fining_period) do |f| %>
  <% if @fining_period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fining_period.errors.count, "error") %> prohibited this fining_period from being saved:</h2>

      <ul>
      <% @fining_period.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fining_week %><br />
    <%= f.number_field :fining_week %>
  </div>
  <div class="field">
    <%= f.label :fine_for_hours_below %><br />
    <%= f.text_field :fine_for_hours_below %>
  </div>
  <div class="field">
    <%= f.label :fine_per_hour_below %><br />
    <%= f.text_field :fine_per_hour_below %>
  </div>
  <div class="field">
    <%= f.label :forgive_percentage_of_fined_hours %><br />
    <%= f.text_field :forgive_percentage_of_fined_hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fining_periods/edit.html.erb
<h1>Editing fining_period</h1>

<%= render 'form' %>

<%= link_to 'Show', @fining_period %> |
<%= link_to 'Back', fining_periods_path %>

app/views/fining_periods/index.html.erb
<h1>Listing fining_periods</h1>

<table>
  <tr>
    <th>Fining week</th>
    <th>Fine for hours below</th>
    <th>Fine per hour below</th>
    <th>Forgive percentage of fined hours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fining_periods.each do |fining_period| %>
  <tr>
    <td><%= fining_period.fining_week %></td>
    <td><%= fining_period.fine_for_hours_below %></td>
    <td><%= fining_period.fine_per_hour_below %></td>
    <td><%= fining_period.forgive_percentage_of_fined_hours %></td>
    <td><%= link_to 'Show', fining_period %></td>
    <td><%= link_to 'Edit', edit_fining_period_path(fining_period) %></td>
    <td><%= link_to 'Destroy', fining_period, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fining period', new_fining_period_path %>

app/views/fining_periods/new.html.erb
<h1>New fining_period</h1>

<%= render 'form' %>

<%= link_to 'Back', fining_periods_path %>

app/views/fining_periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fining week:</b>
  <%= @fining_period.fining_week %>
</p>

<p>
  <b>Fine for hours below:</b>
  <%= @fining_period.fine_for_hours_below %>
</p>

<p>
  <b>Fine per hour below:</b>
  <%= @fining_period.fine_per_hour_below %>
</p>

<p>
  <b>Forgive percentage of fined hours:</b>
  <%= @fining_period.forgive_percentage_of_fined_hours %>
</p>

<%= link_to 'Edit', edit_fining_period_path(@fining_period) %> |
<%= link_to 'Back', fining_periods_path %>