config/routes.rb
WSMA::Application.routes.draw do

  resources :houses
  resources :chores
  resources :shifts
  resources :assignments
  resources :fining_periods
  resources :fines
  resources :preferences
  resources :user_hour_requirements
  resources :house_hour_requirements
  resources :houses
  resources :users

  match "/login" => "users#login"
  match "/logout" => "users#logout"
  match "/forgot_password" => "users#forgot_password"
  match "/reset_password" => "users#reset_password"

  match "/admin" => "admin#index"
  match "/admin/set_admin_active_house" => "admin#set_admin_active_house"

  match "/user/managefines" => "users#manage"
  match "/user/profile" => "users#find_profile"
  match "/user/register" => "users#register"
  match "/user/managers" => "users#managers"
  match "/user/myshift" => "users#myshift"
  match "/users/:id/profile" => "users#profile"
  match "/users/:id/change_password/" => "users#change_password"

  match "/manageshifts" => "shifts#manageshifts"
  match "/createChore" => "chores#createChore"
  match "/quickassign" => "assignments#quickcreate"
  match "users/find_by_name/:name" => "users#find_by_name"
  match "assignments/find/:shift_id/:user_id" => "assignments#find"
  match "/setprefs" => "preferences#set_prefs"
  match "/createprefs" => "preferences#create_prefs"

  match "/demo/advance_time"
  match "/demo/mock_time"
  match "/demo/real_time"

  resources :demo
  match "/demo/chores" => "chores#new"
  match "/demo/myshift" => "users#myshift"

    root :to => 'demo#index'

end

app/models/preference.rb
class Preference < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :shift
  
  validates_numericality_of :rating, :only_integer => true
  validate :rating_has_legal_value
  
  def rating_has_legal_value
    errors.add(:rating, 'must be 0 - 5' ) if not [0, 1, 2, 3, 4, 5].include? rating
  end
  
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @preferences }
    end
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
    @preference = Preference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @preference }
    end
  end

  # GET /preferences/new
  # GET /preferences/new.json
  def new
    @preference = Preference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @preference }
    end
  end

  # GET /preferences/1/edit
  def edit
    @preference = Preference.find(params[:id])
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(params[:preference])

    respond_to do |format|
      if @preference.save
        format.html { redirect_to @preference, :notice => 'Preference was successfully created.' }
        format.json { render :json => @preference, :status => :created, :location => @preference }
      else
        format.html { render :action => "new" }
        format.json { render :json => @preference.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /preferences/1
  # PUT /preferences/1.json
  def update
    @preference = Preference.find(params[:id])

    respond_to do |format|
      if @preference.update_attributes(params[:preference])
        format.html { redirect_to @preference, :notice => 'Preference was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @preference.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference = Preference.find(params[:id])
    @preference.destroy

    respond_to do |format|
      format.html { redirect_to preferences_url }
      format.json { head :ok }
    end
  end
  
  # GET /setprefs
  def set_prefs   
    respond_to do |format|
      format.html { render :action => "setprefs" }
    end
  end
  
  # GET /createprefs
  def create_prefs   
	params.each do |key, value|
		begin
			if Float(key)
				@preference = Preference.create(:user => User.find_by_id(session[:user_id]), :chore => Chore.find_by_id(key.to_i), :rating => value.to_i)
			end
		rescue
			false
		end
	end
    respond_to do |format|
      format.html { render :action => "setprefs" }
    end
  end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_form.html.erb
<%= form_for(@preference) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% @preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preferences/_set_prefs.html.erb
<%= form_tag("/createprefs", :method => "get") do %>
	<% @house = House.find_by_id(User.find_by_id(session[:user_id]).house_id) %>
	<% @chores = @house.chores %>
	<% @chores.each do |chore| %>
		<br />
		<div class="prefChoreName">
			<%= chore.name %>
		</div>
		<br />
		<div class="choreRating">
			<%= radio_button_tag(chore.id, "1") %>	
			<%= label_tag(:rating_1, "Hate/Can't Do") %>					
		</div>
		<div class="choreRating">
			<%= radio_button_tag(chore.id, "2") %>
			<%= label_tag(:rating_2, "Dislike") %>
		</div>
		<div class="choreRating">
			<%= radio_button_tag(chore.id, "3") %>
			<%= label_tag(:rating_3, "Neutral") %>
		</div>
		<div class="choreRating">
			<%= radio_button_tag(chore.id, "4") %>
			<%= label_tag(:rating_4, "Like") %>
		</div>
		<div class="choreRating">
			<%= radio_button_tag(chore.id, "5") %>
			<%= label_tag(:rating_5, "Love") %>
		</div>	
		<br />
	<% end %>	
  <br />
  <div id="prefSubmit">
    <%= submit_tag("Save Preferences") %>
  </div>
  <br />
<% end %>

app/views/preferences/edit.html.erb
<h1>Editing preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @preference %> |
<%= link_to 'Back', preferences_path %>

app/views/preferences/index.html.erb
<h1>Listing preferences</h1>

<table>
  <tr>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @preferences.each do |preference| %>
  <tr>
    <td><%= preference.rating %></td>
    <td><%= link_to 'Show', preference %></td>
    <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
    <td><%= link_to 'Destroy', preference, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Preference', new_preference_path %>

app/views/preferences/new.html.erb
<h1>New preference</h1>

<%= render 'form' %>

<%= link_to 'Back', preferences_path %>

app/views/preferences/setprefs.html.erb
<div id="background">
<h2>Set Preferences</h2>

<%= render 'set_prefs' %>
<div id="setprefsspacer"></div>
</div>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rating:</b>
  <%= @preference.rating %>
</p>


<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>