config/routes.rb
WSMA::Application.routes.draw do

  resources :houses
  resources :chores
  resources :shifts
  resources :assignments
  resources :fining_periods
  resources :fines
  resources :preferences
  resources :user_hour_requirements
  resources :house_hour_requirements
  resources :houses
  resources :users

  match "/login" => "users#login"
  match "/logout" => "users#logout"
  match "/forgot_password" => "users#forgot_password"
  match "/reset_password" => "users#reset_password"

  match "/admin" => "admin#index"
  match "/admin/set_admin_active_house" => "admin#set_admin_active_house"

  match "/user/managefines" => "users#manage"
  match "/user/profile" => "users#find_profile"
  match "/user/register" => "users#register"
  match "/user/managers" => "users#managers"
  match "/user/myshift" => "users#myshift"
  match "/users/:id/profile" => "users#profile"
  match "/users/:id/change_password/" => "users#change_password"

  match "/manageshifts" => "shifts#manageshifts"
  match "/createChore" => "chores#createChore"
  match "/quickassign" => "assignments#quickcreate"
  match "users/find_by_name/:name" => "users#find_by_name"
  match "assignments/find/:shift_id/:user_id" => "assignments#find"
  match "/setprefs" => "preferences#set_prefs"
  match "/createprefs" => "preferences#create_prefs"

  match "/demo/advance_time"
  match "/demo/mock_time"
  match "/demo/real_time"

  resources :demo
  match "/demo/chores" => "chores#new"
  match "/demo/myshift" => "users#myshift"

    root :to => 'demo#index'

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  
  belongs_to :house
  has_many :shifts, :dependent => :destroy
  
  after_initialize :initialize_defaults
  
  validates_presence_of :name, :hours, :sign_out_by_hours_before, :due_hours_after
  validates_numericality_of :hours, :greater_than_or_equal_to => 0, :unless => Proc.new{self.hours.nil?}
  validates_numericality_of :sign_out_by_hours_before, :greater_than_or_equal_to => 0, :unless => Proc.new{sign_out_by_hours_before.nil?}
  validates_numericality_of :due_hours_after, :greater_than_or_equal_to => :hours, :less_than_or_equal_to => 168, :unless => Proc.new{self.hours.nil? or self.due_hours_after.nil?}
  
  def initialize_defaults
    if new_record?
      self.sign_out_by_hours_before = 0 if self.sign_out_by_hours_before.nil?
      self.due_hours_after = self.hours if self.due_hours_after.nil?
    end
  end
  
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController

  before_filter :authenticate, :except => [:login, :logout]
  before_filter :authorize_wsm, :except => [:login, :logout, :show]

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @chores }
    end
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
    @chore = Chore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @chore }
    end
  end

  # GET /chores/new
  # GET /chores/new.json
  def new
    @chore = Chore.new
    @chores = Chore.all
    @shift = Shift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @chore }
    end
  end

  # GET /chores/1/edit
  def edit
    @chore = Chore.find(params[:id])
  end

  # POST /chores
  # POST /chores.json
  def create
    chore_params = params[:chore]
    @user = User.find(session[:user_id])
    chore_params[:house_id] = @user.house_id
    @chore = Chore.new(chore_params)
    @chores = Chore.find_all_by_house_id(@user.house_id)
    @shift = Shift.new
    respond_to do |format|
      if @chore.save

        format.html { redirect_to '/createChore', :notice => 'Chore was successfully created.' }
        format.json { render :json => @chore, :status => :created, :location => @chore }

      else
        format.html { render :action => 'createChore' }
        format.json { render :json => @chore.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chores/1
  # PUT /chores/1.json
  def update
    @chore = Chore.find(params[:id])

    respond_to do |format|
      if @chore.update_attributes(params[:chore])
        format.html { redirect_to '/createChore', :notice => 'Chore was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @chore.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore = Chore.find(params[:id])
    @chore.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :ok }
    end
  end

  def createChore
    @chore = Chore.new
    @user = User.find(session[:user_id])
    @chores = Chore.find_all_by_house_id(@user.house_id)
    @shift = Shift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @chore }
    end
  end
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_edit_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.number_field :hours %>
  </div>
  <div class="field">
    <%= f.label :sign_out_by_hours_before %><br />
    <%= f.number_field :sign_out_by_hours_before %>
  </div>
  <div class="field">
    <%= f.label :due_hours_after %><br />
    <%= f.number_field :due_hours_after %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :house_id %><br />
    <%= f.collection_select(:house_id, House.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :sign_out_by_hours_before %><br />
    <%= f.text_field :sign_out_by_hours_before %>
  </div>
  <div class="field">
    <%= f.label :due_hours_after %><br />
    <%= f.text_field :due_hours_after %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/_shift_form.html.erb
<%= form_for @shift do |f| %>
  <%= f.hidden_field :chore_id, :value=>chore.id %>
  <%= f.hidden_field :temporary, :value=>0 %>
  <%= f.label :day_of_week %>
  <%= f.select(:day_of_week, [['Sunday', 1],
                              ['Monday', 2],
                              ['Tuesday', 3],
                              ['Wednesday', 4],
                              ['Thursday', 5],
                              ['Friday', 6],
                              ['Saturday', 7]]) %><br />
  <%= f.label :time, "Start Time" %>
  <%= f.time_select :time %>



  <%= f.submit :class=>"button" %>
<% end %>

app/views/chores/createChore.html.erb
 <div id="content_header">
        	<h2>Chores</h2>
        </div>

        <!-- Chore creation field -->
        <div id="chore_creation_form">

        <h3> Create a chore </h3>
        <%= form_for @chore do |f| %>
              <% if @chore.errors.any? %>
                <div id="error_explanation">
                 <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

                <ul>
                    <% @chore.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                        <% end %>
                </ul>
                </div>
              <% end %>

              <div class="field"><label>
                <span>Name</span>
                <%= f.text_field :name, :class=>"input_text"%>
              </label></div>
              <div class="field"><label>
                <span>Description</span>
                <%= f.text_area :description, :class=>"description"%>
              </label></div>
              <div class="field"><label>
                <span id=>Duration (hours) <a id="num_hours" class="qbox">[?]</a></span>
                <%= f.number_field :hours, :class=>"input_text", :min=>0%>
              </label></div>
              <div class="field"><label>
                <span>Sign out deadline <a id="sign_out_deadline" class="qbox">[?]</a></span>
                <%= f.number_field :sign_out_by_hours_before, :class=>"input_text", :min=>0%>
              </label></div>
              <div class="field"><label>
                <span>Due hours after <a id="due_hours" class="qbox">[?]</a></span>
                <%= f.number_field :due_hours_after, :class=>"input_text", :min=>0%>
              </label></div>

            <%= f.submit :class=>"button" %>

            <!-- <input name="Submit" type="submit" class="button" value="Create Chore" /> -->




    <% end %>

        </div>

        <div id="chore_list">
        <h3> Created Chores </h3>
        <div id="Accordion1" class="Accordion" tabindex="0">
          <% @chores.each do |chore| %>
              <div class="AccordionPanel">
                <div class="AccordionPanelTab"><%= chore.name %></div>
                <div class="AccordionPanelContent">
                  Description: <%= chore.description %> <br />
                  Hours: <%= chore.hours %> <br />
                  Sign out deadline: <%= chore.sign_out_by_hours_before %> <br />
                  Due hours after: <%= chore.due_hours_after %> <br /> <br />
                  <% for shift in chore.shifts %>
                    <% days_array = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] %>

                        Day: <%= days_array[shift.day_of_week-1] %> <br />
                        Start Time: <%= shift.time.strftime("%I:%M%p") %> <br />
                          <%= button_to 'Edit Shift', edit_shift_path(shift), :method=> :get %>
                    <%= button_to 'Delete Shift', shift, :confirm => 'Are you sure?', :method => :delete %> <br />


                  <% end %>

                  <%= form_for @shift do |f| %>
                      <%= f.hidden_field :chore_id, :value=>chore.id %>
                      <%= f.hidden_field :temporary, :value=>0 %>
                      <%= f.label :day_of_week %>
                      <%= f.select(:day_of_week, [['Sunday', 1],
                                                  ['Monday', 2],
                                                  ['Tuesday', 3],
                                                  ['Wednesday', 4],
                                                  ['Thursday', 5],
                                                  ['Friday', 6],
                                                  ['Saturday', 7]]) %><br />
                      <%= f.label :time, "Start Time" %>
                      <%= f.time_select :time, :ampm => true, :minute_step => 15 %><br />



                      <%= f.submit :class=>"button" %>
                  <% end %>
                   <br />
                  <%= button_to 'Edit Chore', edit_chore_path(chore), :method => :get %>
                  <%= button_to 'Delete Chore', chore, :confirm => 'Are you sure?', :method => :delete %>

                </div>
              </div>
          <% end %>
        </div>
        </div>
      </div>
 <script type="text/javascript">
var Accordion1 = new Spry.Widget.Accordion("Accordion1", { useFixedPanelHeights: false });
$("#num_hours").attr('title', 'Number of hours the chore takes to complete');
$("#sign_out_deadline").attr('title', 'Number of hours before the chore’s assignment time a resident must sign out of the chore to be considered exempt from it.');
$("#due_hours").attr('title', 'How many hours after the chore’s start time the chore is due.');
</script>

<%= link_to 'Back', chores_path %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', new_chore_path %>

app/views/chores/index.html.erb
<h1>Listing chores</h1>

<table>
  <tr>
    <th>House</th>
    <th>Name</th>
    <th>Description</th>
    <th>Hours</th>
    <th>Sign out by hours before</th>
    <th>Due hours after</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chores.each do |chore| %>
  <tr>
	<td><%= chore.house.name %></td>
	<td><%= chore.name %></td>
    <td><%= chore.description %></td>
    <td><%= chore.hours %></td>
    <td><%= chore.sign_out_by_hours_before %></td>
    <td><%= chore.due_hours_after %></td>
    <td><%= link_to 'Show', chore %></td>
    <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
    <td><%= link_to 'Destroy', chore, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chore.name %>
</p>

<p>
  <b>Description:</b>
  <%= @chore.description %>
</p>

<p>
  <b>Hours:</b>
  <%= @chore.hours %>
</p>

<p>
  <b>Sign out by hours before:</b>
  <%= @chore.sign_out_by_hours_before %>
</p>

<p>
  <b>Due hours after:</b>
  <%= @chore.due_hours_after %>
</p>

<p>
  <b>Shifts:</b>
  <ul>
    <% for shift in @chore.shifts %>
      <li><%= link_to shift.time, shift%></li>
    <% end %>
  </ul>
</p>

<p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', new_chore_path %>