config/routes.rb
WSMA::Application.routes.draw do

  resources :houses
  resources :chores
  resources :shifts
  resources :assignments
  resources :fining_periods
  resources :fines
  resources :preferences
  resources :user_hour_requirements
  resources :house_hour_requirements
  resources :houses
  resources :users

  match "/login" => "users#login"
  match "/logout" => "users#logout"
  match "/forgot_password" => "users#forgot_password"
  match "/reset_password" => "users#reset_password"

  match "/admin" => "admin#index"
  match "/admin/set_admin_active_house" => "admin#set_admin_active_house"

  match "/user/managefines" => "users#manage"
  match "/user/profile" => "users#find_profile"
  match "/user/register" => "users#register"
  match "/user/managers" => "users#managers"
  match "/user/myshift" => "users#myshift"
  match "/users/:id/profile" => "users#profile"
  match "/users/:id/change_password/" => "users#change_password"

  match "/manageshifts" => "shifts#manageshifts"
  match "/createChore" => "chores#createChore"
  match "/quickassign" => "assignments#quickcreate"
  match "users/find_by_name/:name" => "users#find_by_name"
  match "assignments/find/:shift_id/:user_id" => "assignments#find"
  match "/setprefs" => "preferences#set_prefs"
  match "/createprefs" => "preferences#create_prefs"

  match "/demo/advance_time"
  match "/demo/mock_time"
  match "/demo/real_time"

  resources :demo
  match "/demo/chores" => "chores#new"
  match "/demo/myshift" => "users#myshift"

    root :to => 'demo#index'

end

app/models/house_hour_requirement.rb
class HouseHourRequirement < ActiveRecord::Base
  belongs_to :house
  
  validates_presence_of :week, :hours
  validates_numericality_of :week, :hours, :greater_than_or_equal_to => 0
  validates_uniqueness_of :week, :scope => [:house_id]
  
end

app/controllers/house_hour_requirements_controller.rb
class HouseHourRequirementsController < ApplicationController

  # GET /house_hour_requirements
  # GET /house_hour_requirements.json
  def index
    @house_hour_requirements = HouseHourRequirement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @house_hour_requirements }
    end
  end

  # GET /house_hour_requirements/1
  # GET /house_hour_requirements/1.json
  def show
    @house_hour_requirement = HouseHourRequirement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @house_hour_requirement }
    end
  end

  # GET /house_hour_requirements/new
  # GET /house_hour_requirements/new.json
  def new
    @house_hour_requirement = HouseHourRequirement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @house_hour_requirement }
    end
  end

  # GET /house_hour_requirements/1/edit
  def edit
    @house_hour_requirement = HouseHourRequirement.find(params[:id])
  end

  # POST /house_hour_requirements
  # POST /house_hour_requirements.json
  def create
    @house_hour_requirement = HouseHourRequirement.new(params[:house_hour_requirement])

    respond_to do |format|
      if @house_hour_requirement.save
        format.html { redirect_to @house_hour_requirement, :notice => 'House hour requirement was successfully created.' }
        format.json { render :json => @house_hour_requirement, :status => :created, :location => @house_hour_requirement }
      else
        format.html { render :action => "new" }
        format.json { render :json => @house_hour_requirement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /house_hour_requirements/1
  # PUT /house_hour_requirements/1.json
  def update
    @house_hour_requirement = HouseHourRequirement.find(params[:id])

    respond_to do |format|
      if @house_hour_requirement.update_attributes(params[:house_hour_requirement])
        format.html { redirect_to @house_hour_requirement, :notice => 'House hour requirement was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @house_hour_requirement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /house_hour_requirements/1
  # DELETE /house_hour_requirements/1.json
  def destroy
    @house_hour_requirement = HouseHourRequirement.find(params[:id])
    @house_hour_requirement.destroy

    respond_to do |format|
      format.html { redirect_to house_hour_requirements_url }
      format.json { head :ok }
    end
  end
end

app/helpers/house_hour_requirements_helper.rb
module HouseHourRequirementsHelper
end

app/views/house_hour_requirements/_form.html.erb
<%= form_for(@house_hour_requirement) do |f| %>
  <% if @house_hour_requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house_hour_requirement.errors.count, "error") %> prohibited this house_hour_requirement from being saved:</h2>

      <ul>
      <% @house_hour_requirement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :house_id %><br />
    <%= f.collection_select(:house_id, House.all, :id, :name) %>
  </div>
  
  <div class="field">
    <%= f.label :week %><br />
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/house_hour_requirements/edit.html.erb
<h1>Editing house_hour_requirement</h1>

<%= render 'form' %>

<%= link_to 'Show', @house_hour_requirement %> |
<%= link_to 'Back', house_hour_requirements_path %>

app/views/house_hour_requirements/index.html.erb
<h1>Listing house_hour_requirements</h1>

<table>
  <tr>
    <th>House</th>
    <th>Week</th>
    <th>Hours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @house_hour_requirements.each do |house_hour_requirement| %>
  <tr>
    <td><%= house_hour_requirement.house.name %></td>
    <td><%= house_hour_requirement.week %></td>
    <td><%= house_hour_requirement.hours %></td>
    <td><%= link_to 'Show', house_hour_requirement %></td>
    <td><%= link_to 'Edit', edit_house_hour_requirement_path(house_hour_requirement) %></td>
    <td><%= link_to 'Destroy', house_hour_requirement, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New House hour requirement', new_house_hour_requirement_path %>

app/views/house_hour_requirements/new.html.erb
<h1>New house_hour_requirement</h1>

<%= render 'form' %>

<%= link_to 'Back', house_hour_requirements_path %>

app/views/house_hour_requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>House:</b>
  <%= link_to @house_hour_requirement.house.name, @house_hour_requirement.house %>
</p>

<p>
  <b>Week:</b>
  <%= @house_hour_requirement.week %>
</p>

<p>
  <b>Hours:</b>
  <%= @house_hour_requirement.hours %>
</p>


<%= link_to 'Edit', edit_house_hour_requirement_path(@house_hour_requirement) %> |
<%= link_to 'Back', house_hour_requirements_path %>